name: salt_version

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  salt_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Gather Salt version
        uses: oprypin/find-latest-tag@v1
        with:
          repository: saltstack/salt
          regex: '^v\d{4}(\.\d+)?$'
        id: salt_version_orig

      - name: Clean up version
        run: |
          export version='${{ steps.salt_version_orig.outputs.tag }}'
          echo "::set-output name=tag::${version#?}"
        id: salt_version

      - name: Update version string
        run: sed -i "1c\FROM docker.io/saltstack/salt:${{ steps.salt_version.outputs.tag }}" Dockerfile

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: ':arrow_up: Bump saltstack/salt to ${{ steps.salt_version.outputs.tag }}'
          body: 'https://docs.saltproject.io/en/latest/topics/releases/${{ steps.salt_version.outputs.tag }}.html'
          commit-message: ':arrow_up: Bump saltstack/salt to ${{ steps.salt_version.outputs.tag }}'
          labels: dependencies
          branch: saltstack/${{ steps.salt_version.outputs.tag }}
          delete-branch: true
